# Generated by Django 3.1.5 on 2021-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='name',
            field=models.CharField(default='image', max_length=100),
        ),
    ]
